language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
notifications:
    email: false
script:
  - yarn build
  - zip -q netlify-cms.zip -r dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: netlify-cms.zip
  all_branches: true
  on:
    tags: true
